
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  application:
    name: FILE-UPLOAD
  mail:
    host: smtp.gmail.com
    port: 587
    username: samugale5555@gmail.com
    password: dtimgmjmowyjxhzv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
